// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [{ name: "newtable1", columns: [] }] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Newtable1 = InferredTypes["newtable1"];
export type Newtable1Record = Newtable1 & XataRecord;

export type DatabaseSchema = {
  newtable1: Newtable1Record;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://ws-fdrujb.eu-central-1.xata.sh/db/test",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
